### ISSUE TITLE
Problem downloading URL

### ISSUE THREAD

**Issue by Chris00** [mirage/ocaml-cohttp#239]
The following code
```ocaml
open Lwt
open Printf
module Client = Cohttp_lwt_unix.Client

let get url =
  Client.get url >>= fun (_, b) ->
  Cohttp_lwt_body.to_string b >>= fun data ->
  Lwt_io.printf "%s\n%!" data

let () =
  Lwt_main.run(get (Uri.of_string "http://blog.camlcity.org/blog/rss"))
```
fails to download the complete body of the URL.

**Comment by rgrinberg** [comment]
Thanks for the report. This is indeed an issue.

The cause of this is Gerd's blog not returning any `content-length`. In that case cohttp simply tries to fill some fixed size buffer that ends up being a truncated version of the body [1]. We should probably try to read the content more eagerly here with some timeout for nothing being read perhaps. I'm open to suggestions.

P.S. You can reproduce these problems much easier if you simply use the `cohttp_curl_{lwt,async}.native` utility rather than writing up a snippet.

[1] https://github.com/mirage/ocaml-cohttp/blob/master/lib/transfer_io.ml#L80

**Comment by Chris00** [comment]
On Sun, 25 Jan 2015 16:59:09 -0800, Rudi Grinberg wrote:
> 
> Thanks for the report. This is indeed an issue.
> 
> The cause of this is Gerd's blog not returning any
> content-length. In that case cohttp simply tries to fill some fixed
> size buffer that ends up being a truncated version of the body [1].

One should read until the fd gives an end-of-file condition.  And,
yes, a timeout would be nice — but that is not too difficult for the
user to add one with Lwt.

> P.S. You can reproduce these problems much easier if you simply use the
> cohttp_curl_{lwt,async}.native utility rather than writing up a snippet.

Thanks for letting me know.
