### ISSUE TITLE
[RENAMED] Cohttp cannot directly connect to an IP

### ISSUE THREAD

**Issue by SGrondin** [mirage/ocaml-cohttp#240]
Client.call makes one DNS lookup per call. Under load, this becomes problematic. Right now there doesn't seem to be any way around it, because it's not possible to connect to an IP and pass the hostname as a header since Cohttp will add a second Host header with the IP!

So either implement some sort of DNS caching, or -even better- DO NOT add a Host header if it's already present.

**Comment by rgrinberg** [comment]
Hmm, that's very annoying. I assume this problem is backend independent (i.e. async/lwt). Indeed it seems like the correct thing to do is to allow for ip address and let the user set the host manually.

**Comment by avsm** [comment]
This is correct -- the default behaviour of `Conduit_resolver_lwt` (which Cohttp_lwt_unix invokes to perform the URI resolution) is to call `gethostbyname`.  Cohttp allows you to override the default resolver, and so the caching layer should go into `Conduit_resolver_lwt`. 

I see no harm in doing this, although technically that caching should be the job of the stub resolver configured by your OS (which can cache results).  More options are better here, since you may want to cache everything more aggressively than the TTL allows for some use cases. 

Cohttp should not add a Host header if one is already present in the request.

**Comment by SGrondin** [comment]
The bug seems to come from https://github.com/mirage/ocaml-cohttp/blob/ba298cc8e6eea3f0d18e25611748e6e5452f69c8/lib/request.ml#L113 and possibly https://github.com/mirage/ocaml-cohttp/blob/ba298cc8e6eea3f0d18e25611748e6e5452f69c8/lib/request.ml#L97 . I would fix it myself if I was more confident in my OCaml skills. It's a blocking bug for me at the moment that's causing me tons of issues.

Whoever fixes it and publishes a hotfix to OPAM will be my hero.

**Comment by rgrinberg** [comment]
@SGrondin something like this?

https://github.com/rgrinberg/ocaml-cohttp/tree/hotfix_sgrondin

**Comment by SGrondin** [comment]
@rgrinberg THANK YOU SO MUCH. I'm building it to run my tests on it right now. I'll let you know how it goes.

**Comment by SGrondin** [comment]
It works great. I applied your commit on top of the cohttp version tag I'm using and it's perfect. Thank you again. I'm keeping an eye on the official repo so that I can switch back to the official release once it's merged.

**Comment by SGrondin** [comment]
This seems to have been fixed here: https://github.com/mirage/ocaml-cohttp/blob/074ac23f5ef6eec14714650ed0247f0f91ebe69c/lib/request.ml#L126
If so, it can be closed.
