### ISSUE TITLE
Port Cohttp_async to Async_kernel

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#279]
New as of ocaml/opam-repository#3679

**Comment by hhugo** [comment]
There is still a tiny dependency on Thread and Unix.
`base/async/kernel/lib/debug.ml`

**Comment by avsm** [comment]
opened janestreet/async_kernel#6

**Comment by marklrh** [comment]
I want to have a better understanding of the steps of resolving this issue.

After discussing with @rgrinberg , I feel the steps should be the following. Please correct me if I am wrong or there is a better way.

We want to make cohttp-async functions like cohttp-lwt now (Mirage-able, js_of_ocaml-able), so we want to have a similar design as cohttp-lwt. To do this, we should

1.  starting to use conduit, which also means to make conduit support async (using ``async_kernel``)

2. write ``cohttp_async``, then ``cohttp_async_unix``, basically just like the design of cohttp-lwt

At first, I think this is a trivial issue, but it turns out to be harder than I thought. 

All comments are welcomed.

**Comment by rgrinberg** [comment]
Unlikely to happen as there's really not much demand for this. And janestreet has their own cohttp + async + jsoo package.
