### ISSUE TITLE
cohttp-server-lwt ignores the `host` parameter

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-cohttp#285]
See https://github.com/mirage/ocaml-conduit/issues/42

**Comment by marklrh** [comment]
I believe the reason is [this line](https://github.com/mirage/ocaml-cohttp/blob/master/lwt/cohttp_lwt_unix.mli#L76).

We did not provide ``~ctx`` to ``Server.create``, and ``Server.create`` has to use the default ``ctx``, which is defined at [here](https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_lwt_unix.ml#L144).

Then, the program turns out to use default ctx at [L343 in ``cohttp_lwt_unix.ml``](https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_lwt_unix.ml#L343).

**Comment by marklrh** [comment]
and I think we should use [``custom_ctx``](https://github.com/mirage/ocaml-cohttp/blob/master/lwt/cohttp_lwt_unix_net.ml#L42) in ``cohttp_lwt_unix_net.ml``, which means we should probably use [``init``](https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_lwt_unix.ml#L147) in ``conduit_lwt_unix.ml``.

I am not pretty sure about the conclusion I derived. I will be glad if someone can check my suggestion.

**Comment by dsheets** [comment]
#298 uses essentially @marklrh's suggestion. I also put an interface on `Cohttp_lwt_unix_net` and marked it private.
