### ISSUE TITLE
Async client doesn't support reusing connections

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cohttp#331]
Unlike the lwt clients which supports reusing connections through the `callv` function.

@avsm I'm inclined to consider this as 1.0 blocker as well.

cc @trevorsummerssmith

**Comment by trevorsummerssmith** [comment]
I'd be happy to implement this, as I'm needing this. @avsm @rgrinberg did you have any thoughts on the interface? I'm still on the wrong side of the learning curve when it comes to idiomatic async code. Would one create a similar high level interface as with lwt, and use a Pipe (or Async_stream)? Or would it make more sense to just a lowerlevel Conduit_async.io type passed around?

**Comment by rgrinberg** [comment]
Copying the lwt interface but using pipes is probably not a bad idea. It's not an ideal interface but it should definitely be included.

I think a lower level interface as you've proposed would be nice to have as well.

**Comment by avsm** [comment]
Connection handling consists of a few separate things:

* For one outgoing connection, to do HTTP pipelining and get a set of requests and responses in order.  This is what the Lwt `callv` does.
* Something to manage *multiple* outgoing HTTP connections to a single origin server, and dispatch a set of incoming HTTP requests and get the response.  This may also need to parse HTTP error codes to understand if it's ok to retransmit a request down a different connection.
* The other thing to bear in mind is the impending HTTP2, which will support out-of-order responses, so any interface here would ideally not be tied to being serialised.  We do a pretty good job of this today already, but need to keep it in mind.

So I would suggest doing the simple `callv` single-Conduit-TCP/SSL interface initially, and then build a higher-level multiple-connection dispatcher.  There may be some load balancing logic in Async already for the latter -- it's worth asking on the Core mailing list if you can't find anything as it seems like a common requirement.

**Comment by trevorsummerssmith** [comment]
@avsm Agree that those other things should be done. cc @rgrinberg I need keep-alives right now and was just thinking a simple interface that did no pipelining initially, and then adding pipeling later. There's really two issues here:

1) Have a client use keep alives.
2) Have a client do pipelineing.

To implement 1 we need to add some notion of state (the connection) to the api. The LWT implementation currently does this by passing around a `ctx`.

Question 1: do we want to break the current client interface and add a parameter like this to every call (eg get, post, put)?

Answer: I think we should, because having some abstract context is a good extension point anyway. However I don't know how much you all care about breaking the interface.

So I'd suggest that I expose the Cohttp_async.Net module, add a new abstract type to the Client and have every current call take one of these.

Then at a later point in time we can add another call that does pipelining.

Obviously if you all want to not break interfaces then we'd need to do something else. Thoughts?

**Comment by rgrinberg** [comment]
I don't think that breaking compatibility is necessary for keep alives. A pipe based `callv` implementation can support keep alives. The connection's lifetime is tied to the pipe's.

**Comment by trevorsummerssmith** [comment]
Makes sense. I should have said "it seems not ideal to have only a single call implement keep alives" but as long as it is possible (ie with a single call) that is better than not possible. I'm ok with that.

**Comment by rgrinberg** [comment]
@trevorsummerssmith this is now in master and is slated for the next release.

**Comment by trevorsummerssmith** [comment]
Awesome thanks Rudi. I'll give it some testing this week.
