### ISSUE TITLE
204 behaviour

### ISSUE THREAD

**Issue by edwintorok** [mirage/ocaml-cohttp#371]
According to the RFC you can't send [`Transfer-Encoding`](http://tools.ietf.org/html/rfc7230#section-3.3.1) or [`Content-Length`](http://tools.ietf.org/html/rfc7230#section-3.3.2) for a 204 reply.
Cohttp adds one of these always though.

**Comment by rgrinberg** [comment]
It's a bit of a problem that our current code cannot tell the difference between an empty body and the absence of a body. Such a distinction would be useful here.

**Comment by avsm** [comment]
Is such a distinction material?  In most responses, the empty/nil body cases are freely interchangeable.  HTTP 204 is specifically a No Content response, and so we should treat it like a HEAD request and ensure that no body headers get added.

**Comment by rgrinberg** [comment]
This distinction might not be material for this particular issue but I think giving the user the power to choose whether a bodyless response should include a content encoding header. Can't think of a use case right now.

I'm just a little easy with taking away control from the user as cohttp is supposed to be a "low level" library. I guess this doesn't take away any control because the user may still create a malformed response by adding his own `content-length: 0` header.

My other qualm with this kind of stuff is that we don't really have a systematic approach to enforcing http variants. Our current approach seems more like "do it when it's convenient". Anyway, my lack of concrete suggestion is basically equivalent of punting the problem to the user which isn't any better. So this is just armchair philosophy at the end.

Fine, let's make sure we aren't adding encoding headers for 204's with empty bodies.

**Comment by avsm** [comment]
Yeah, it's certainly true that what was a low-level HTTP library has been adding convenience features (like the magic addition of encoding headers) that nudge it into the higher levels, and not in a principled way.

**Comment by rgrinberg** [comment]
@avsm I've made a fix for this.

I still think that it it's desirable to tell the difference between a user not providing a body, and a user providing an empty body.

**Comment by edwintorok** [comment]
I've opened a separate issue about a more systematic approach to enforce the MUST constraints from the RFC, I think we need access to both the request and the reply to perform such validation though (for compatibility we could assume the request is an empty GET if not provided).
I'm not sure whether users should be permitted to send malformed replies that violate the RFC, but the low-level API of Cohttp probably should with appropriate warnings in the docs.
