### ISSUE TITLE
Responses are written serially, rather than in parallel?

### ISSUE THREAD

**Issue by jonathanyc** [mirage/ocaml-cohttp#450]
I've been puzzling over the cohttp code to see if it it might work for a project.
Looking at the request/response handling in `cohttp_lwt.ml`, I saw this:

```ocaml
  let callback spec io_id ic oc =
    let conn_id = Connection.create () in
    let conn_closed () = spec.conn_closed (io_id,conn_id) in
    (* The server operates by reading requests into a Lwt_stream of requests
       and mapping them into a stream of responses serially using [spec]. The
       responses are then sent over the wire *)
    let req_stream = request_stream ic in
    let res_stream = response_stream spec.callback io_id conn_id req_stream in
    (* Clean up resources when the response stream terminates and call
     * the user callback *)
    Lwt_stream.on_terminate res_stream conn_closed;
    (* Transmit the responses *)
    res_stream |> Lwt_stream.iter_s (fun (res,body) ->
      let flush = Response.flush res in
      Response.write ~flush (fun writer ->
        Body.write_body (Response.write_body writer) body
      ) res oc
    )

```

Is there a reason `Lwt_stream.iter_s` is used instead of `Lwt_stream.iter_p`? In the situation where I am serving a number of large files, it seems like using `iter_p` would allow Lwt to write to multiple clients instead of waiting for the write to one client to fully complete. Otherwise the whole server could become bottlenecked by a single client.

I'm sure there is a good reason why `iter_s` is used, I'd just like to know it! :smile:

**Comment by dsheets** [comment]
Hi @jonathanyc, `callback` is called for a single client's connection. The request stream in this function is for an HTTP pipeline of requests which must be responded to in order (HTTP does not have message identifiers) which is why `Lwt_stream.map_s` and `Lwt_stream.iter_s` are used. `Cohttp_lwt_unix.Server.create` calls `Conduit_lwt_unix.serve` which, in the case of plain TCP, calls `Conduit_lwt_unix.Sockaddr_server.init` which runs an `accept` loop for simultaneous client connections.
