### ISSUE TITLE
Getting an https site fails

### ISSUE THREAD

**Issue by ciniglio** [mirage/ocaml-cohttp#598]
Trying to retrieve: https://taylorpearson.me/feed/

Fails with:
`"SSL connection() error: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error"`

I've tried using both the `tls` opam package and the `ssl` opam package with openssl 1.0.2n and 1.1.0g

**Comment by ryanslade** [comment]
I'm seeing the same issue using cohttp-async

**Comment by mseri** [comment]
Looking at the provided handshake, I think this is an instance of https://github.com/mirleft/ocaml-tls/issues/362

**Comment by drvink** [comment]
This is likely due to widening deployment of TLS 1.3. I've fixed this for the OpenSSL bindings in savonet/ocaml-ssl#45. TLS 1.3 does not seem to be implemented in the native OCaml TLS implementation yet, according to [this comment](https://github.com/mirleft/ocaml-tls/issues/386#issuecomment-430520138).

**Comment by hannesm** [comment]
with the rise of tls 0.12.0 (and upcoming 0.12.1), establishing a connection to the above mentioned server works fine. feel free to re-open this issue in case you still have issues to connect to the server.
