### ISSUE TITLE
Get rid of encoding in the request type

### ISSUE THREAD

**Issue by mseri** [mirage/ocaml-cohttp#801]
On the server side, it’s completely redundant as its’ always in the headers
On the client side, it needs to be provided with the body and not the request

**Comment by avsm** [comment]
I _think_ the reason I did that was for proxies -- a proxy might want to add a transfer-encoding header to override the content encoding to (e.g.) send a large body downstream  as chunked encoding.  It's been many years since I wrote a HTTP proxy in cohttp though -- @djs55 might have am more recent use in vpnkit.

**Comment by mseri** [comment]
Ping @rgrinberg

**Comment by rgrinberg** [comment]
Thanks for making the issue.

It will still be possible to implement such a proxy even without these fields. Accepting the request for the proxy will be the same, but to re-encode to transfer-encoding, the proxy will  send a body created with a transfer-encoding or constructor downstream.

**Comment by avsm** [comment]
That sounds right -- no objection from me to this change!

**Comment by mseri** [comment]
Deprecation is addressed by https://github.com/mirage/ocaml-cohttp/pull/805
