### ISSUE TITLE
Please backport to v4 support for cmdliner >= 1.2.0

### ISSUE THREAD

**Issue by glondu** [mirage/ocaml-cohttp#991]
At the moment, in my environment, I'm still getting ocaml-cohttp 4.0.0 which is vulnerable to the issue fixed by c9c1e60cfd2f08a3b56711c3a7b01f2bbd50b2bd. It seems to be due to a conflict with cmdliner 1.2.0. Please consider backporting support for cmdliner >= 1.2.0 and making a release in the 4.x series.

I'm stuck to 4.x because of ocsigenserver. Cf https://github.com/ocsigen/ocsigenserver/issues/228

**Comment by mseri** [comment]
Also the tests and the examples?

**Comment by mseri** [comment]
I think the issue is that cohttp-lwt-unix  until recently used to ship three binaries: https://github.com/mirage/ocaml-cohttp/tree/v4-backports/cohttp-lwt-unix/bin

These need to be ported to cmdliner >= 1.1 for the package to work. It should be a relatively small patch, like https://github.com/mirage/ocaml-cohttp/commit/4cd36b5f19df9628fd9b84dbdccf95420cf4ee6c

i will see if I find 5 minutes to do it

**Comment by mseri** [comment]
A release with the compatibility is submitted to the opam-repo. I am going to close the issue

**Comment by mseri** [comment]
I would recommend ocsigen to update to 5, version 4 is no longer maintained

**Comment by glondu** [comment]
Thank you for your prompt reaction!

> I would recommend ocsigen to update to 5, version 4 is no longer maintained

Agreed. I made a PR to ocsigenserver: https://github.com/ocsigen/ocsigenserver/pull/229 and meanwhile, I added a custom patch in belenios: https://github.com/glondu/belenios/commit/2efdfbf4ef0effd93348bead1b5ad6e91b842236
